### ISSUE TITLE
Question about function **nan

### ISSUE THREAD

**Issue by Fangwq** [mjlaine/dlm#1]
I‘m confused by the function like sumnan, stdnan. It will come out an error  when run the code
`Undefined` function or variable 'sumnan'.
Can you clear up my confusion ? Thanks.

**Comment by mjlaine** [comment]
The toolbox needs Matlab files in mcmcstat toolbox: https://github.com/mjlaine/mcmcstat. Including sumnan etc.

**Comment by Fangwq** [comment]
Thanks a lot. It seems I only got the old version of mcmcstat in the first place.
